/* Generated by gba/tools/make_assets.py - do not edit. */
#ifndef ASSETS_H
#define ASSETS_H
#include <stdint.h>

#define ELFIN_ROM_SIZE 32768
#define PIX_COUNT 19325
#define CONTRIB_COUNT 28626
#define SEG_COUNT 512
#define INK_R 22
#define INK_G 24
#define INK_B 30

extern const uint8_t elfin_rom[ELFIN_ROM_SIZE];
extern const uint16_t bg_bitmap[240 * 160];
extern const uint16_t pix_off[PIX_COUNT];
extern const uint16_t pix_bg[PIX_COUNT];
extern const uint16_t pix_first[PIX_COUNT];
extern const uint8_t pix_n[PIX_COUNT];
extern const uint16_t c_seg[CONTRIB_COUNT];   /* bit 15 = shadow */
extern const uint8_t c_alpha[CONTRIB_COUNT];
extern const uint16_t seg_start[SEG_COUNT + 1];
extern const uint16_t seg_list[];

#endif
